In [1]:
import pandas as pd
#Input Excel File, change path accordingly
raw_dir = "/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Data/RAPID_18_19.xlsx"
raw_df=pd.read_excel(io=raw_dir)
# print(raw_df.columns)
raw_df.head()

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.


/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")


0.0

In [2]:
trim_df = raw_df[["LVO","Side","site occlusion","CTA CTP Report Text","RAPID Core","RAPID Penumbra"]]
trim_df.head()

LVO Side site occlusion                                CTA CTP Report Text  \
0    0  NaN            NaN  EXAMINATION: Computed tomography angiography (...   
1    0  NaN            NaN  EXAMINATION: Computed tomography angiography (...   
2    0  NaN            NaN  EXAMINATION: Computed tomography angiography (...   
3    0  NaN            NaN  EXAMINATION: Computed tomography angiography (...   
4    0  NaN            NaN  EXAMINATION: Computed tomography angiography (...   

   RAPID Core  RAPID Penumbra  
0         NaN             NaN  
1        13.0             5.0  
2         NaN             NaN  
3         NaN             NaN  
4         NaN             NaN

In [3]:
#Uncertain LVO 1?
# trim_df.iloc[504]

In [4]:
#Filter if LVO uncertain
# filtered_df = trim_df[~trim_df["LVO"].str.contains("?",regex=False).fillna(False)]
# filtered_df.iloc[50]
filtered_df = trim_df

In [5]:
#Function that reads the angio report cerebral artery table
#from pandas dataframe
#and outputs a python dictionary
#
#If "no occlusion" is present for a given artery, value is marked as 0
#Otherwise, the program looks to free-body text for clarification
#These values are marked with 'None'
import copy
import re

class ca_templates_reader:
    
    def __init__(self,df_column):
        
        self.df_column = df_column
        
        #cerebral arteries dictionary
        self.main_dict = {
            "L CCA": None,
            "L carotid bifurcation": None,
            "L ICA proximal": None,
            "L ICA distal": None,
            "L ICA terminus": None,
            "L M1": None,
            "L M2 branches": None,
            "L A2": None,
            "R CCA": None,
            "R carotid bifurcation": None,
            "R ICA proximal": None,
            "R ICA distal": None,
            "R ICA terminus": None,
            "R M1": None,
            "R M2 branches": None,
            "R A2": None,
            "L Vertebral Artery": None,
            "R Vertebral Artery": None,
            "Basilar Artery": None,
            "L PCA": None,
            "R PCA": None

        }
        
        self.ca_pattern_dict = copy.deepcopy(self.main_dict)
    
    def compile_regex(self):
        #Compiling regex patterns of the cerebral artery strings
        #For optimal performance
        
        for ca in self.ca_pattern_dict:
            self.ca_pattern_dict[ca]=re.compile(ca+':.*\n')
        
    
    def read_ca_template(self, text):
        
        #Example cerebral arteries template line:
        #R CCA: No occlusion or significant stenosis

        no_occlusion = re.compile('(n|N)o occlusion')
    #     for file in raw_text_files:
        curr_dict = copy.deepcopy(self.main_dict)
        for ca in curr_dict:
            #Searching for template text for each cerebral artery
            #Some follow up reports may not have the template
            
            search = self.ca_pattern_dict[ca].search(text)
            if search is not None:
                #string of ca template line
                sent = search.group()
                #print(sent)
                #Expect match most cases, change dict value to 0 (no occlusion)
                #If 'no occlusion' not in cerebral a. desc, leave with None value (default flag)
                #Will determine later
                if no_occlusion.search(sent) is not None:
                    curr_dict[ca] = 0
        return curr_dict
    #         ca_dicts.append(curr_dict)
    
    def read_templates(self):
        #List to store the cerebral artery dictionaries for report
        ca_dicts = []
        for report in self.df_column:
            ca_dicts.append(self.read_ca_template(report))
        return ca_dicts

In [6]:
ctr = ca_templates_reader(filtered_df["CTA CTP Report Text"])
ctr.compile_regex()

In [7]:
class report_text_extractor:
    
    def __init__(self, df_column):
        self.df_column = df_column
        self.report_template_pattern = re.compile('Left anterior circulation:[\s\S]*IMPRESSION', re.I)
        #List of all cerebral artery templates from the reports
        self.report_templates = self.extract_from_reports(self.report_template_pattern)


        self.impression_pattern = re.compile('IMPRESSION:[\s\S]*', re.I)
        #List of all impressions from the reports
        self.impressions = self.extract_from_reports(self.impression_pattern)
        
        #List of all CT Perfusion sections from reports
        self.ctp_pattern = re.compile('CT Perfusion:[\s\S]*IMPRESSION', re.I)
        self.ctp_sections = self.extract_from_reports(self.ctp_pattern)
        
        
    def get_report_templates(self):
        return self.report_templates
    
    def get_impressions(self):
        return self.impressions

    def get_ctps(self):
        return self.ctp_sections
    
    def extract_from_reports(self,pattern):
        report_extractions = []
        for report in self.df_column:
            search = pattern.search(report)
            if search:
                report_extractions.append(search.group())
            else:
                report_extractions.append(None)
        return report_extractions


In [8]:
# rte = report_text_extractor(filtered_df["CTA CTP Report Text"])
# templates = rte.get_report_templates()
# impressions = rte.get_impressions()
# ctps = rte.get_ctps()
# print(templates[163])
# print('/'*50)
# print(impressions[163])
# print('/'*50)
#Extract ischemic core volume and hypoperfusion values in mLprint(ctps[522])

Left anterior circulation:
L CCA: no occlusion or significant stenosis
L carotid bifurcation: no occlusion or significant stenosis
L ICA proximal: no occlusion. Moderate stenosis secondary to atherosclerotic plaque.
L ICA distal: no occlusion or significant stenosis
L ICA terminus: There is atherosclerosis of the supraclinoid left internal carotid artery with resultant near complete occlusion versus occlusion at the left internal carotid artery terminus.  This appears similar to the prior CT angiogram from --/--/----.  The left anterior cerebral artery and middle cerebral artery likely fill via the circle of Willis.
L M1: no occlusion or significant stenosis. Mildly diminished caliber. 
L M2 branches: no occlusion or significant stenosis
L A2: no occlusion or significant stenosis
There are diminished distal vessels on the left within the parietal lobe at the site of prior infarct. 

Right anterior circulation:
R CCA: no occlusion or significant stenosis
R carotid bifurcation: no occlus

In [9]:
#Extract ischemic core and hypoperfusion volumes in mL
class ctp_volumes_extractor:
    def __init__(self,ctp_sections_list):
        self.ctps = ctp_sections_list
        self.volume_pattern = re.compile('[0-9]* mL')
        self.volumes = []
        
    def extract_volumes(self):
        for ctp in self.ctps:
            if ctp:
                #List of 2 strings ex. ['0 mL', '146 mL']
                search = self.volume_pattern.findall(ctp)
                if search:                      
                    #['0 mL', '146 mL'] -> (0, 146)
                    vol_tup = tuple([int(vol_text.split()[0]) if len(vol_text.split()) > 1 else None
                                     for vol_text in search])
                    self.volumes.append(vol_tup)
                else:
                    self.volumes.append(None)
            else:
                self.volumes.append(None)

    #List of tuples of format (ischemic core volume,hypoperfusion volume)
    def get_volumes(self):
        return self.volumes
        
        

In [10]:
ctp_str = '''
CT Perfusion:

Estimated ischemic core volume (rCBF < 0.3): 177 mL
Estimated hypoperfusion volume (Tmax > 6 sec): 320 mL


IMPRESSION:'''
test_ctp = [ctp_str]
ctpve = ctp_volumes_extractor(test_ctp)
ctpve.extract_volumes()
ctpve.get_volumes()

[(177, 320)]

In [11]:
# print(filtered_df["CTA CTP Report Text"].iloc[172])

EXAMINATION: Computed tomography angiography (CTA) of the head without and with contrast; Computed tomography angiography (CTA) of the neck with contrast._x000D_
CT perfusion imaging of the head with contrast_x000D_
_x000D_
HISTORY: Left-sided weakness._x000D_
_x000D_
TECHNIQUE: Computed tomography of the head was performed without contrast according to standard protocol. Computed tomographic angiography was obtained from the level of the aortic arch to the vertex following the uneventful administration of intravenous contrast according to hyperacute stroke protocol. 3D images were generated on a dedicated workstation._x000D_
CT perfusion of the brain was performed with intravenous contrast using a separate data acquisition. The data was transmitted to a separate workstation for processing by RAPID software (iSchemaView) to produce automated calculations of the estimated cerebral blood flow and Tmax._x000D_
_x000D_
Contrast information:_x000D_
125 mL Optiray-350_x000D_
_x000D_
COMPARIS

In [12]:
# ctr.read_ca_template(templates[8])


{'L CCA': 0,
 'L carotid bifurcation': None,
 'L ICA proximal': 0,
 'L ICA distal': 0,
 'L ICA terminus': 0,
 'L M1': 0,
 'L M2 branches': 0,
 'L A2': 0,
 'R CCA': 0,
 'R carotid bifurcation': None,
 'R ICA proximal': None,
 'R ICA distal': None,
 'R ICA terminus': None,
 'R M1': None,
 'R M2 branches': None,
 'R A2': 0,
 'L Vertebral Artery': 0,
 'R Vertebral Artery': 0,
 'Basilar Artery': 0,
 'L PCA': 0,
 'R PCA': 0}

In [13]:
# ca_templates_dicts = ctr.read_templates()
# ca_templates_dicts[52]

{'L CCA': 0,
 'L carotid bifurcation': 0,
 'L ICA proximal': 0,
 'L ICA distal': 0,
 'L ICA terminus': 0,
 'L M1': 0,
 'L M2 branches': 0,
 'L A2': 0,
 'R CCA': 0,
 'R carotid bifurcation': 0,
 'R ICA proximal': 0,
 'R ICA distal': 0,
 'R ICA terminus': 0,
 'R M1': 0,
 'R M2 branches': 0,
 'R A2': 0,
 'L Vertebral Artery': None,
 'R Vertebral Artery': None,
 'Basilar Artery': 0,
 'L PCA': 0,
 'R PCA': 0}

In [14]:
#For empty values in the ca_dicts, need to check impression
#NLP needs to be used here ex.'Occlusion of the proximal inferior left M2 branch'
#NLP needed on midline shift ex. There is no mass effect or midline shift.
import networkx as nx
import pyConTextNLP.pyConText as pyConText
import pyConTextNLP.itemData as itemData

In [15]:
modifiers = itemData.get_items("/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/modifiers.yml")
targets = itemData.get_items("/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/targets.yml")

/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/pyConTextNLP/itemData.py:40: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  context_items =  [contextItem((d["Lex"],


In [16]:
#pyConTextNLP uses yml files to store entities and their regex pattern information
#This function is to be used for quick lookup of an entity for short term use
#Or to add new entities to a yml file

#"/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/modifiers.yml"
#"/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/targets.yml"

class pyConText_itemData_initializer:
    
    def __init__(self, modifiers_path=None, targets_path=None):
        if modifiers_path is None:
            self.modifiers_path = "https://raw.githubusercontent.com/chapmanbe/pyConTextNLP/master/KB/lexical_kb_05042016.yml"
        else:
            self.modifiers_path = modifiers_path
            
        self.modifiers = itemData.get_items(self.modifiers_path)
        self.targets = []
            
        if targets_path is not None:
            self.targets_path = targets_path
            self.targets = itemData.get_items(self.targets_path)
    
    def add_target(self,entity,category='', regex='', direction=''):
        self.targets.append(itemData.contextItem([entity,category,regex,direction]))
        
        #Code from pyConTextNLP itemData.py
        #def get_items(_file): context_items =  [contextItem((d["Lex"], d["Type"],r"%s"%d["Regex"],d["Direction"])) for d in yaml.load_all(f0)]
    
    def add_entity_to_yml(self, yml_path, entity, category="''", regex="''", direction="''"):
        yml_entity = "Direction: "+ direction + "\n" + \
        "Lex: "+ entity + "\n" + \
        "Regex: "+ regex + "\n" + \
        "Type: " + category + "\n" + \
        "---\n" 
        
        with open(yml_path, "r+") as f:
            old = f.read()
            f.seek(0)
            #Prepending
            f.write(yml_entity + old)
            
        f.close()
        
    def get_itemData(self):
        return self.modifiers,self.targets
        


In [17]:
mod_path = "/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/modifiers.yml"
targ_path = "/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/targets.yml"
itemData_init = pyConText_itemData_initializer(mod_path,targ_path)
itemData_init.modifiers[3]

literal<<\bl\b>>; category<<['left_side']>>; re<<\bl\b>>; rule<<forward>>

In [18]:
type(itemData_init.targets[0])

pyConTextNLP.itemData.contextItem

In [19]:
# itemData_init.add_target('occlusion')
itemData_init.targets[0]

literal<<occlusion>>; category<<['occlusion']>>; re<<(occlusion|occlusive|occluded)>>; rule<<bidirectional>>

In [20]:
#itemData_init.add_entity_to_yml("/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/targets.yml",'P1')

In [21]:
#Function to determine existence or rule out given entity
#Ex. Midline shift/No midline shift
#Ex. Occlusion/No occlusion

#Input is string entity that you want to rule in/out
#***Since words have DIFFERENT forms, consider using a PREFIX INSTEAD
#Ex. Entity: occlusion; sentence contains 'occluded thrombus'
# Using the prefix 'occlu' would capture both in a rudimentary fashion

class modifier_target_finder:
    def __init__(self, sentence, mod_itemData, targ_itemData):
        self.modifiers = mod_itemData
        self.targets = targ_itemData
        self.sentence = sentence
        
        self.markup = pyConText.ConTextMarkup()
        self.markup.setRawText(sentence.lower())
        self.markup.cleanText()
        
        self.markup.markItems(self.modifiers,mode="modifier")
        self.markup.markItems(self.targets,mode="target")
        self.markup.applyModifiers()
    
    #New addition
    def log(self):
        print(self.markup.__str__())
        
    
    def get_markup(self):
        return list(self.markup.edges())
            
    def find_mod_target_pair(self,desired_modifier,modifier_attrib,desired_target,target_attrib):
        #set removes duplicates
        return list(set([(modifier.getLiteral(),target.getLiteral()) 
                for (modifier,target) in self.markup.edges() 
                # getattr() will run modifier/target . getLiteral()/categoryString()/getTagID()/getConTextCategory()
                if (desired_modifier in getattr(modifier,modifier_attrib)() 
                    and desired_target in getattr(target,target_attrib)())]))
    
    
    #Returns 0 if negated
    #Returns 1 if present and not negated
    #Returns 2 if confirmed existence
    #Returns None if not in sentence
    def confirm_existence(self, entity, entity_type):
        entities = []
        for modifier,target in self.markup.edges():
            etype_func = {"getLiteral":[modifier.getLiteral,target.getLiteral],
                          "categoryString":[modifier.categoryString,target.categoryString]}
            for func in etype_func[entity_type]:
                entities.append(func())
        if entity in entities:
            neg_pairs_list = self.find_mod_target_pair('negated_existence','categoryString',entity,entity_type)
            if neg_pairs_list:
                return 0
            def_exis_pairs_list = self.find_mod_target_pair(('definite_existence'),
                                                    'categoryString', entity,entity_type)
            prob_exis_pairs_list = self.find_mod_target_pair(('definite_existence'),
                                                            'categoryString', entity,entity_type)
            if def_exis_pairs_list or prob_exis_pairs_list:
                return 2
            return 1
        else:
            return None
    

In [22]:
# test_str = "Chronic left frontal and parietal infarcts with paucity of vessels within the distal MCA vessels at the site of chronic parietal infarct. "
# mtf = modifier_target_finder(test_str,
#                              itemData_init.get_itemData()[0],itemData_init.get_itemData()[1])
# mtf.get_markup()

[(<id> 110817854851893856320707927580509592686 </id> <phrase> left </phrase> <category> ['left_side'] </category> ,
  <id> 110842944826398873551137051078701997166 </id> <phrase> frontal </phrase> <category> ['brain_anatomy'] </category> ),
 (<id> 110817854851893856320707927580509592686 </id> <phrase> left </phrase> <category> ['left_side'] </category> ,
  <id> 110842955918341625548144314174855044206 </id> <phrase> parietal </phrase> <category> ['brain_anatomy'] </category> ),
 (<id> 110817854851893856320707927580509592686 </id> <phrase> left </phrase> <category> ['left_side'] </category> ,
  <id> 110842791123763595878322119603438345326 </id> <phrase> mca </phrase> <category> ['mca_circulation'] </category> ),
 (<id> 110817854851893856320707927580509592686 </id> <phrase> left </phrase> <category> ['left_side'] </category> ,
  <id> 110842968594847627830438329141887097966 </id> <phrase> parietal </phrase> <category> ['brain_anatomy'] </category> ),
 (<id> 110817854851893856320707927580509

In [23]:
# if mtf.find_mod_target_pair("negated_existence","categoryString","uncertain_flow","categoryString"):
#     print(True)

In [24]:
# mtf.confirm_existence("uncertain_occlusion","categoryString")

In [25]:
#Extract midline shift yes/no
#Searches entire report for midline shift sentence,
#as it is discussed at beginning of Findings section
#exclusively
class midline_shift_extractor:
    def __init__(self,df_column,modifiers,targets):
        self.df_column = df_column
        self.modifiers = modifiers
        self.targets = targets
        self.midline_shift_pattern = re.compile('([^.]*?midline shift[^.]*\.)')
        self.midline_shift_statuses = []
        
    def extract_midline_shifts(self):
        for report in self.df_column:
            search = self.midline_shift_pattern.search(report)
            if search:
                sent = search.group()
                mtf = modifier_target_finder(sent,self.modifiers,self.targets)
                status = mtf.confirm_existence("midline shift","getLiteral")
                if status == 0:
                    self.midline_shift_statuses.append(0)
                elif status > 0:
                    self.midline_shift_statuses.append(1)
                else:
                    self.midline_shift_statuses.append(None)
    
    def get_midline_shifts(self):
        return self.midline_shift_statuses
                
            

In [26]:
# mse = midline_shift_extractor(filtered_df["CTA CTP Report Text"],itemData_init.get_itemData()[0],itemData_init.get_itemData()[1])
# mse.extract_midline_shifts()
# midline_shifts = mse.get_midline_shifts()
# midline_shifts

In [27]:
# [i for i, value in enumerate(midline_shifts) if value == 1] 
#Only 2 out of 500 have midline shift, will not run in final function

In [28]:
# filtered_df['CTA CTP Report Text'][211]

In [29]:
#ca = cerebral arteries
#expects ca_templates_reader dictionary as input
#which acts as a filter.
#For sites not ruled out (value=None), read the impression
#for further clarification

class possible_occlusions_generator:    
    def __init__(self, ca_filter_dict):
        
        self.new_dict_keys = ["L CCA", "L ICA", "L ACA", "L A1", "L A2", "L A3", "L A4", "L A5",
                        "L MCA", "L M1", "L M2", "L M3", "L M4",
                        "R CCA", "R ICA", "R ACA", "R A1", "R A2", "R A3", "R A4", "R A5",
                        "R MCA", "R M1", "R M2", "R M3", "R M4",
                        "L vertebral", "L V1", "L V2", "L V3", "L V4",
                        "R vertebral", "R V1", "R V2", "R V3", "R V4",
                        "basilar",
                        "L PCA", "L P1", "L P2", "L P3", "L P4",
                        "R PCA", "R P1", "R P2", "R P3", "R P4"]
    
        
        self.filter_dict = self.consolidate_dict(ca_filter_dict)
        self.filled_dict = self.fill_in_dict(self.filter_dict)
        self.ca_to_investigate = [key for key,value in self.filled_dict.items() if value < 0]
        
    def negate_nones(self,dictionary):
        negated_dict = {}
        for key,value in dictionary.items():
            if value is None:
                negated_dict[key] = -1
            else:
                negated_dict[key] = value
        return negated_dict
            
    def consolidate_keys_for_dict(self,dictionary,list_of_keys,consol_key):
        new_dict = {}
        consolidated_value = 0
        found_key = 0
        for key,value in dictionary.items():
            if found_key == 1:
                #Add consol_key to new_dict at spot of first key in list_of_keys 
                new_dict[consol_key] = consolidated_value
            if key in list_of_keys:
                found_key+=1                
                #Value is negative, indicating further investigation
                consolidated_value += value                
            else:
                new_dict[key] = value
        new_dict[consol_key] = consolidated_value
        return new_dict
    
    #Calls consolidate_keys_for_dict to consolidate CCAs and ICAs
    def consolidate_dict(self,filter_dict):
        consol_dict = self.negate_nones(filter_dict)
        keys_dict = {
            "L CCA": ["L CCA", "L carotid bifurcation"],
            "R CCA": ["R CCA", "R carotid bifurcation"],
            "L ICA": ["L ICA proximal","L ICA distal","L ICA terminus"],
            "R ICA": ["R ICA proximal","R ICA distal","R ICA terminus"],
            "L M2": ["L M2 branches"],
            "R M2": ["R M2 branches"],
            "R vertebral": ["R Vertebral Artery"],
            "L vertebral": ["L Vertebral Artery"],
            "basilar": ["Basilar Artery"]
        }
        for consol_key,list_of_keys in keys_dict.items():
            consol_dict = self.consolidate_keys_for_dict(consol_dict,list_of_keys,consol_key)
        
        return consol_dict
    
    
    #Adds AX, MX, PX, and VX segments, where X is segment location (ex. V4, X=4)
    def fill_in_dict(self,consol_dict):
        
        new_dict = {}
        
        #Populate keys-vals from previous consolidated dictionary
        for key in self.new_dict_keys:
            if key in consol_dict:
                new_dict[key] = consol_dict[key]
            else:
                #Temp value that will be filled by transfer_key_values
                new_dict[key] = None
        
        #The template serves as a reference for which cerebral arteries to look at
        #This function transfers the values from the template to the corresponding
        #AX, MX, PX, VX arteries
        #Ex. L Vertebral Artery Occlusion indicates occlusion in one/more of L V1-4
        def transfer_key_values(source_key,list_receiving):
            for key in list_receiving:
                if key == "L MCA":
                    new_dict[key] = consol_dict["L M1"]+consol_dict["L M2"]
                elif key == "R MCA":
                    new_dict[key] = consol_dict["R M1"]+consol_dict["R M2"]
                else:
                    new_dict[key] = consol_dict[source_key]
        refs = {
            "L M1/M2": ["L MCA"],
            "R M1/M2": ["R MCA"],
            "L M2": ["L M3", "L M4"],
            "R M2": ["R M3", "R M4"],
            "L A2": ["L ACA","L A1", "L A3", "L A4", "L A5"],
            "R A2": ["R ACA","R A1", "R A3", "R A4", "R A5"],
            "L vertebral": ["L V1", "L V2", "L V3", "L V4"],
            "R vertebral": ["R V1", "R V2", "R V3", "R V4"],
            "L PCA": ["L P1", "L P2", "L P3", "L P4"],
            "R PCA": ["R P1", "R P2", "R P3", "R P4"]
        }
        
        for source_key,list_receiving in refs.items():
            transfer_key_values(source_key,list_receiving)
            
        return new_dict
    
    def get_possibilities(self):
        return self.ca_to_investigate

In [30]:
from itertools import compress
class occlusions_investigator:
    
    def __init__(self,ca_to_investigate,impressions_txt,modData,targData):
        self.modData = modData
        self.targData = targData
        self.impressions_txt = impressions_txt
        self.ca_to_investigate = ca_to_investigate
        
        self.extra_chars = re.compile('IMPRESSION:|\n[0-9]\.|\r|\n|\t')
        self.impressions = re.sub(self.extra_chars,'',self.impressions_txt)
        self.txt_sents = self.impressions.split(".")
        #List of 0,1,2 or Nones based on negated occ, occ mentioned, occ confirmed, or no occ mentioned
        self.sent_has_occlusion = [self.confirm_occlusion(sent) for sent in self.txt_sents]
        self.sent_maybe_occlusion = [self.confirm_uncertain_occlusion(sent) for sent in self.txt_sents]
        self.occlusions = []
        self.bool_none = lambda x: False if not x else True
        self.filt_sent_has_occlusion = list(filter(self.bool_none,self.sent_has_occlusion))
        self.filt_txt_sents = list(compress(self.txt_sents,map(self.bool_none,self.sent_has_occlusion)))
        self.filt_maybe_sents = list(compress(self.txt_sents,map(self.bool_none,self.sent_maybe_occlusion)))
        #0 for negation
        #1 for occlusion present and not negated
        #2 for occlusion indicated
        #None for occlusion not found
        self.occlusion_ratings = []
        
        #This list keeps track of occlusion sentences that have and have not
        #been matched with an occlusion in the template
        #Those unmatched with template will be flagged for the user to review
        self.unmatched_occlusion_sents = [True for sent in self.filt_txt_sents]
        
        #Find if sentence refers to cerebral artery with indeterminate terms
        #Will be flagged for user review
        self.uncertain_occlusions = []
        
        self.markups = []

    def get_occlusions(self):
        
        ca_to_investigate = []
        for potential in self.ca_to_investigate:
            side = None
            ca = None
            if " " in potential:
                potential_list = potential.split(" ")
                side = potential_list[0]
                ca = potential_list[1]
            else:
                ca = potential
            
            ca_to_investigate.append((potential,side,ca))
        
        #Check for uncertain occlusions
        if self.sent_maybe_occlusion:
            #print(self.sent_maybe_occlusion)
            for sent in self.filt_maybe_sents:
                for potential,side,ca in ca_to_investigate:
                    lim = self.confirm_limitation(sent, ca)
                    if lim:
                        self.uncertain_occlusions.append(lim)
        
        #There is no occlusion in any sentence
        #Return empty occlusions list
        if not self.filt_sent_has_occlusion:
            self.occlusion_ratings = [None for pos in self.ca_to_investigate]
            return self.occlusions

        #Investigate potenial occlusions by side and cerebral artery
        for potential,side,ca in ca_to_investigate:
            #for sent,occl_label in zip(self.filt_txt_sents,self.filt_sent_has_occlusion):
            for i in range(len(self.filt_txt_sents)):
                sent = self.filt_txt_sents[i]
                occl_label = self.filt_sent_has_occlusion[i]
                #If site/side of occlusion verified
                #Add the potential occlusion to the final occlusions list
                is_occl, flag = self.confirm_site_occlusion(sent,side,ca)
                #Excludes both None and 0, runs on 1 or 2
                if is_occl:
                    self.unmatched_occlusion_sents[i] = False
                    if flag == -1:
                        #side of the site could not be verified, flag -1
                        #in occlusion_ratings list
                        self.occlusion_ratings.append((sent,side,ca,flag))
                        #Marked as non-occlusion for now
                        occl_label = 0
                    else:
                        #Can be corellated to filt_sent_has_occlusion list with labels 0-2
                        self.occlusion_ratings.append((sent,side,ca,occl_label))
            
                    if occl_label > 0:
                        self.occlusions.append(potential)
                else:
                    #is_occl
                    #None: Means potential occlusion not found in Findings
                    #0: Occlusion negated
                    self.occlusion_ratings.append((sent,side,ca,None))
                        
            
        self.unmatched_occlusion_sents = list(compress(self.filt_txt_sents,self.unmatched_occlusion_sents))
        

        #If other side has no findings and occlusion of that artery present
        #Then add to occlusions list
        def check_other_side_occlusion(side,ca,occl_label):
            
            vs_dict = {"ACA": ["A1","A2","A3","A4","A5"],
                       "MCA": ["M1","M2","M3","M4"],
                       "PCA": ["P1","P2","P3","P4"],
                       "vertebral": ["V1","V2","V3","V4"]
                      }
            
            other_side = None
            if side == "L":
                other_side = "R"
            elif side == "R":
                other_side = "L"
            for o_sent, o_side, o_ca, o_occl_label in self.occlusion_ratings:
                #Most cases will be a list of one element
                #Ex. M2
                ca_list = [ca]
                #Need to check other side segment equivalents
                #If general large vessel a possible occlusion
                #Ex. L MCA -> Check R M1, R M2, R M3, R M4
                if ca in vs_dict:
                    for c in vs_dict[ca]:
                        ca_list.append(c)
                for ca_equiv in ca_list:
                    #Check if other side, same cerebral artery and occlusion label is 0,1,2
                    #If so this occlusion is not likely
                    #Otherwise, add this occlusion
                    if o_occl_label is not None:
                        if o_side == other_side and o_ca == ca_equiv and o_occl_label > -1:
                            return
            self.occlusions.append(side + " " + ca)

        #Check flagged occlusions where side and cerebral artery didn't match
        for sent,side,ca,occl_label in self.occlusion_ratings:
            if occl_label == -1:             
                check_other_side_occlusion(side,ca,occl_label)
                

        return self.occlusions
    
    def get_possibility_ratings(self):
        return self.occlusion_ratings
    
    def get_markups(self):
        #(index,sents with occlusion, markup of those sents)
        return list(zip(self.filt_txt_sents,self.markups))
    
    def get_unmatched_occlusion_sents(self):
        return self.unmatched_occlusion_sents
    
    def get_uncertain_occlusions(self):
        return self.uncertain_occlusions


    def confirm_occlusion(self,sent):
        mtf = modifier_target_finder(sent,self.modData,self.targData)
        #Looking for occlusion in acute context, not chronic occlusion
        if not mtf.find_mod_target_pair('chronic','getLiteral','occlusion','getLiteral'):
            #either 0, 1, 2, or None
            return mtf.confirm_existence('occlusion','getLiteral')
        else:
            return None
        
    def confirm_uncertain_occlusion(self,sent):
        mtf = modifier_target_finder(sent,self.modData,self.targData)
        uo = mtf.confirm_existence('uncertain_occlusion','categoryString')
        if uo:
            return uo
        uf = mtf.confirm_existence('uncertain_flow','categoryString')
        if uf:
            return uf
        return None


    def confirm_site_occlusion(self,sent,side,site):
        mtf = modifier_target_finder(sent,self.modData,self.targData)
        self.markups.append(mtf.get_markup())
        full_side = side
        if side == "L":
            full_side = "left_side"
        elif side == "R":
            full_side = "right_side"

        #Verify occlusion of specific cerebral artery
        sites = mtf.find_mod_target_pair(site,'getLiteral','occlusion','getLiteral')
        
        #Verify side of specific cerebral artery
        #None gets overwritten later, flag -1 important
        if sites:
            if side is None:
                return (True,None)
            sides_sites = mtf.find_mod_target_pair(full_side,'categoryString',site,'getLiteral')
            if sides_sites:
                return (True,None)
            else:
                #could not verify the side corresponds to site in findings
                return (True,-1)
        return (False,None)
    
    #Sentences with terms that may or may not suggest acute occlusion
    #Are flagged for user review
    def confirm_limitation(self, sent, site):
        mtf = modifier_target_finder(sent,self.modData,self.targData)
        if mtf.find_mod_target_pair('uncertain_occlusion','categoryString',site,'getLiteral'):
            return ('uncertain occlusion',site,sent)
        if mtf.find_mod_target_pair('uncertain_flow','categoryString',site,'getLiteral'):
            if mtf.find_mod_target_pair('negated_existence','categoryString','uncertain_flow','categoryString'):
                return ('uncertain negated flow',site,sent)
        return None
        
        

In [31]:
u = ('t1','t2')
p = ('t3')
zip('t1','t2','t3')

In [32]:
# occlusions_list = filtered_edges(('anterior_circulation' or 'posterior_circulation'),'categoryString','occlusion','categoryString')
# side_circ_list = []
# #occlusions_list = [('M1', 'occlusion'), ('M2', 'occlusion')]
# for (modifier,target) in occlusions_list:
#     #side_circ_list = [('right', 'M1'), ('right', 'M2')]
#     side_circ_list += filtered_edges('side','categoryString',modifier,'getLiteral')
# for side,circ in side_circ_list:
#     #list evaluates to [('no', 'occlusion')], or is empty
#     no_occlusion = filtered_edges('negated_existence','categoryString','occlusion','categoryString')
#     if no_occlusion:
#         print("No occlusion at "+ side + " " + circ)
#     else:
#         print("Occlusion at "+ side + " " + circ)

# # else:
# #     for (modifier,target) in occlusions_list:
# #             print("occlusion at " + occlusions_list[0])

In [33]:
# test_dict = ca_templates_dicts[163]
# test_dict

{'L CCA': 0,
 'L carotid bifurcation': 0,
 'L ICA proximal': 0,
 'L ICA distal': 0,
 'L ICA terminus': None,
 'L M1': 0,
 'L M2 branches': 0,
 'L A2': 0,
 'R CCA': 0,
 'R carotid bifurcation': 0,
 'R ICA proximal': 0,
 'R ICA distal': None,
 'R ICA terminus': 0,
 'R M1': 0,
 'R M2 branches': 0,
 'R A2': 0,
 'L Vertebral Artery': None,
 'R Vertebral Artery': 0,
 'Basilar Artery': 0,
 'L PCA': 0,
 'R PCA': 0}

In [34]:
# pog = possible_occlusions_generator(test_dict)
# pog.filter_dict

{'L CCA': 0,
 'L ICA': -1,
 'L M1': 0,
 'L M2': 0,
 'L A2': 0,
 'R CCA': 0,
 'R ICA': -1,
 'R M1': 0,
 'R M2': 0,
 'R A2': 0,
 'L vertebral': -1,
 'R vertebral': 0,
 'basilar': 0,
 'L PCA': 0,
 'R PCA': 0}

In [35]:
# pog.filled_dict

{'L CCA': 0,
 'L ICA': -1,
 'L ACA': 0,
 'L A1': 0,
 'L A2': 0,
 'L A3': 0,
 'L A4': 0,
 'L A5': 0,
 'L MCA': 0,
 'L M1': 0,
 'L M2': 0,
 'L M3': 0,
 'L M4': 0,
 'R CCA': 0,
 'R ICA': -1,
 'R ACA': 0,
 'R A1': 0,
 'R A2': 0,
 'R A3': 0,
 'R A4': 0,
 'R A5': 0,
 'R MCA': 0,
 'R M1': 0,
 'R M2': 0,
 'R M3': 0,
 'R M4': 0,
 'L vertebral': -1,
 'L V1': -1,
 'L V2': -1,
 'L V3': -1,
 'L V4': -1,
 'R vertebral': 0,
 'R V1': 0,
 'R V2': 0,
 'R V3': 0,
 'R V4': 0,
 'basilar': 0,
 'L PCA': 0,
 'L P1': 0,
 'L P2': 0,
 'L P3': 0,
 'L P4': 0,
 'R PCA': 0,
 'R P1': 0,
 'R P2': 0,
 'R P3': 0,
 'R P4': 0}

In [36]:
# possibilities = pog.get_possibilities()
# possibilities

['L ICA', 'R ICA', 'L vertebral', 'L V1', 'L V2', 'L V3', 'L V4']

In [37]:
# print(filtered_df["CTA CTP Report Text"].iloc[325])

EXAMINATION: Computed tomography angiography (CTA) of the head with contrast; Computed tomography angiography (CTA) of the neck with contrast._x000D_
CT perfusion imaging of the head with contrast_x000D_
_x000D_
HISTORY: Left hemiparesis and right conjugate gaze deviation, suspected hyperacute stroke._x000D_
_x000D_
TECHNIQUE: Computed tomography of the head was performed without contrast according to standard protocol. Computed tomographic angiography was obtained from the level of the aortic arch to the vertex following the uneventful administration of intravenous contrast according to hyperacute stroke protocol. 3D images were generated on a dedicated workstation._x000D_
CT perfusion of the brain was performed with intravenous contrast using a separate data acquisition. The data was transmitted to a separate workstation for processing by RAPID software (iSchemaView) to produce automated calculations of the estimated cerebral blood flow and Tmax._x000D_
_x000D_
Contrast information:_

In [38]:
# oi = occlusions_investigator(possibilities,impressions[325],itemData_init.get_itemData()[0],itemData_init.get_itemData()[1])
# predicted_occlusions = oi.get_occlusions()
# predicted_occlusions

['L vertebral']

In [39]:
# #predicted_occlusions vs possibilities
# extra_poss = list(set(predicted_occlusions) - set(possibilities))
# extra_poss

[]

In [40]:
# oi.unmatched_occlusion_sents

['_x000D__x000D_  Acute ischemic stroke characterized by partial occlusion of the right posterior cerebral artery mid-proximal P1 segment']

In [41]:
# oi.uncertain_occlusions

[]

In [42]:
# oi.confirm_uncertain_occlusion('cut-off')

In [43]:
# oi.confirm_limitation('Abrupt cut off of distal right M2/ proximal M3 with geographic paucity of vasculature compared to contralateral side. ','M2')

('uncertain occlusion',
 'M2',
 'Abrupt cut off of distal right M2/ proximal M3 with geographic paucity of vasculature compared to contralateral side. ')

In [44]:
# oi.filt_txt_sents

['_x000D__x000D_  Acute ischemic stroke characterized by partial occlusion of the right posterior cerebral artery mid-proximal P1 segment',
 '_x000D__x000D_  Long segment occlusion of the right vertebral artery extending from the right subclavian artery origin to the C4 vertebral level with distal diminutive reconstitution']

In [45]:
#oi.occlusion_ratings
# oi.get_possibility_ratings()

[('_x000D__x000D_  Acute ischemic stroke characterized by partial occlusion of the right posterior cerebral artery mid-proximal P1 segment',
  'L',
  'ICA',
  None),
 ('_x000D__x000D_  Long segment occlusion of the right vertebral artery extending from the right subclavian artery origin to the C4 vertebral level with distal diminutive reconstitution',
  'L',
  'ICA',
  None),
 ('_x000D__x000D_  Acute ischemic stroke characterized by partial occlusion of the right posterior cerebral artery mid-proximal P1 segment',
  'R',
  'ICA',
  None),
 ('_x000D__x000D_  Long segment occlusion of the right vertebral artery extending from the right subclavian artery origin to the C4 vertebral level with distal diminutive reconstitution',
  'R',
  'ICA',
  None),
 ('_x000D__x000D_  Acute ischemic stroke characterized by partial occlusion of the right posterior cerebral artery mid-proximal P1 segment',
  'L',
  'vertebral',
  None),
 ('_x000D__x000D_  Long segment occlusion of the right vertebral arter

In [46]:
# oi.filt_sent_has_occlusion

[1, 1]

In [47]:
# oi.sent_has_occlusion

[1, 1, None, None, None, None, None]

In [48]:
# oi.sent_maybe_occlusion

[None, None, None, None, None, None, None]

In [49]:
# oi.filt_txt_sents

['_x000D__x000D_  Acute ischemic stroke characterized by partial occlusion of the right posterior cerebral artery mid-proximal P1 segment',
 '_x000D__x000D_  Long segment occlusion of the right vertebral artery extending from the right subclavian artery origin to the C4 vertebral level with distal diminutive reconstitution']

In [50]:
class vessel_site_classifier:
    
    def __init__(self,occl_list):
        self.occl_list = occl_list
        #Large vessels: CCA, ICA, ACA, MCA, PCA, Vertebrals, Basilar
        #Segments (of large vessels):
        #A1-5, M1-4, V1-4, P1-4
        self.vessels = []
        self.sites = []
        self.vs_dict = {"CCA": [],
                       "ICA": [],
                       "ACA": ["A1","A2","A3","A4","A5"],
                       "MCA": ["M1","M2","M3","M4"],
                       "PCA": ["P1","P2","P3","P4"],
                       "vertebral": ["V1","V2","V3","V4"],
                       "basilar": []}
    def classify(self):
        for occlusions in self.occl_list:
            vessel_occlusions = []
            site_occlusions = []
            for occlusion in occlusions:
                if len(occlusion.split()) > 1:
                    side = occlusion.split()[0]
                    occl = occlusion.split()[1]
                else:
                    side = ''
                    occl = occlusion
                if occl in self.vs_dict.keys():
                    vessel_occlusions.append(side + " " + occl)
                else:
                    for vessel,segments in self.vs_dict.items():
                        if occl in segments:
                            vessel_occlusions.append(side + " " + vessel)
                            #Ex ('MCA', 'L')
                            site_occlusions.append(side + " " + occl)
            #list(set()) removes duplicates (ex. multiple MCA occlucions -> ['MCA'])
            self.vessels.append(list(set(vessel_occlusions)))
            self.sites.append(site_occlusions)
        return self.vessels,self.sites
                
            

In [51]:
# #Test vessel_site_classifier
# test_vsc = vessel_site_classifier([predicted_occlusions])
# predicted_vessel_occ, predicted_segments_occ = test_vsc.classify()
# lower = lambda x:x.lower()

In [52]:
# predicted_vessel_occ

[['L vertebral']]

In [53]:
# predicted_segments_occ

[[]]

In [54]:
# list(set(map(lower,predicted_vessel_occ[0])))

['l vertebral']

In [55]:
l = lambda q:q.split()[-1]
f = [" MCA","R ICA", "L vertebral","L ICA"]
list(set(map(l,f)))
#s.split()[-1]

['ICA', 'vertebral', 'MCA']

In [56]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import accuracy_score
class stats_generator:
    def __init__(self, X, y, check_side=None):
        self.oneHotEncoder = MultiLabelBinarizer()
        
        if check_side:
            #Get the 'L', or 'R' if there is a side, or put "None"
            self.splitter = lambda w:w.split()[0] if ('L' in w) or ('R' in w) else 'None'
        else:
            #Get rid of side labels
            #["L MCA"] -> ["MCA"]
            #***Merges both side occlusions ex. ["R MCA","L MCA"] -> ["MCA"]
            self.splitter = lambda l:l.split()[-1]
        self.X = [list(set(map(self.splitter,i))) for i in X]
        self.y = [list(set(map(self.splitter,i))) for i in y]
        #If only self.y, classes in self.X not in self.y would
        #cause an error when classification_report(...) generated
        #Case where predictions vary from y labels 
        self.oneHotEncoder.fit(self.y+self.X)
        self.encoded_X = self.oneHotEncoder.transform(self.X)
        self.encoded_y = self.oneHotEncoder.transform(self.y)
    def getStats(self):
        print(classification_report(self.encoded_y, self.encoded_X, target_names=self.oneHotEncoder.classes_))
        print(multilabel_confusion_matrix(self.encoded_y, self.encoded_X))
        print(accuracy_score(self.encoded_y, self.encoded_X))
        
        
        
#         self.vessels = ["CCA","ICA","ACA","MCA","PCA","vertebral","basilar"]
#         self.sites = ["A1","A2","A3","A4","A5","M1","M2","M3","M4","P1","P2","P3","P4","V1","V2","V3","V4"]
        
        

In [57]:
# testX = [['R basilar'],['L vertebral'],['L MCA','L ICA']]
# testy = [['L vertebral', ' basilar', 'R vertebral'],['L vertebral'],['L ICA']]
# sg = stats_generator(testX, testy)
# print(sg.encoded_X)
# print(sg.encoded_y)
# sg.oneHotEncoder.classes_

[[0 0 1 0]
 [0 0 0 1]
 [1 1 0 0]]
[[0 0 1 1]
 [0 0 0 1]
 [1 0 0 0]]


array(['ICA', 'MCA', 'basilar', 'vertebral'], dtype=object)

In [58]:
# print(classification_report(sg.encoded_y, sg.encoded_X, target_names=sg.oneHotEncoder.classes_))

              precision    recall  f1-score   support

         ICA       1.00      1.00      1.00         1
         MCA       0.00      0.00      0.00         0
     basilar       1.00      1.00      1.00         1
   vertebral       1.00      0.50      0.67         2

   micro avg       0.75      0.75      0.75         4
   macro avg       0.75      0.62      0.67         4
weighted avg       1.00      0.75      0.83         4
 samples avg       0.83      0.83      0.78         4



/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [59]:
# # testX = [['R basilar'],['L vertebral'],[]]
# # testy = [['L vertebral', ' basilar', 'R vertebral'],['L vertebral'],['R MCA']]
# sg = stats_generator(testX, testy, "sides")
# print(sg.encoded_X)
# print(sg.encoded_y)
# sg.oneHotEncoder.classes_

[[0 0 1]
 [1 0 0]
 [1 0 0]]
[[1 1 1]
 [1 0 0]
 [1 0 0]]


array(['L', 'None', 'R'], dtype=object)

In [60]:
# print(classification_report(sg.encoded_y, sg.encoded_X, target_names=sg.oneHotEncoder.classes_))

              precision    recall  f1-score   support

           L       1.00      0.67      0.80         3
        None       0.00      0.00      0.00         1
           R       1.00      1.00      1.00         1

   micro avg       1.00      0.60      0.75         5
   macro avg       0.67      0.56      0.60         5
weighted avg       0.80      0.60      0.68         5
 samples avg       1.00      0.78      0.83         5



/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [61]:
class labels_extractor:
    
    def __init__(self,side_column,occlusion_column):
        self.side_labels = self.extract_occlusion_labels(side_column)
        self.occl_labels = self.extract_occlusion_labels(occlusion_column)
    
    def extract_occlusion_labels(self,df):
        #side = (df['Side'])
        cleaned_df = list(df.fillna(''))

        #df_normalize_both = [df.lower() if "both" in df.lower() else df for df in cleaned_df]

        df_no_spaces = [df.replace(" ","") for df in cleaned_df]

        df_no_seps = [re.split("\/|&",df) if ("/" in df or "&" in df) else df for df in df_no_spaces]


        return df_no_seps
    
    def return_labels(self):
        labels = []
        for side, occl in zip(self.side_labels,self.occl_labels):
            #Occl is '', i.e. no occlusion
            if not occl:
                labels.append([])
            else:
                #Lowercase vertebral and basilar to match predictions
                if occl in ["Vertebral", "Basilar"]:
                    occl = occl.lower()
                #Ex. ["M2", "M1"]
                if isinstance(occl,list):
                    #Ex. ["L", "R"]
                    if isinstance(side,list):
                        labels.append([" ".join(tup) for tup in zip(side,occl)])
#                         for s, o in zip(side,occl):
#                             labels.append(s + " " + o)
                    else:
                        if side:
                            side += " "
                        l = []
                        for o in occl:
                            if "both" in side.lower():
                                l.append("R "+ o)
                                l.append("L "+ o)
                            else:
                                l.append(side + o)
                        labels.append(l)
                else:
                    if side:
                        side += " "
                    if "both" in side.lower():
                        labels.append(["R "+ occl, "L "+ occl])
#                         l.append("R "+ occl)
#                         l.append("L "+ occl)
                    else:
                        labels.append([side + occl])
        return labels
                        
                    

    
# side_labels = extract_occlusion_labels(filtered_df['Side'])
# side_labels
# le = labels_extractor(filtered_df['Side'],filtered_df['site occlusion'])
# le.side_labels[421]

['R', 'R', 'L']

In [62]:
# occl_labels = extract_occlusion_labels(filtered_df['site occlusion'])
# occl_labels
# le.occl_labels[452]

['Vertebral', 'Basilar', 'ICA']

In [63]:
# labels = le.return_labels()
# labels[452]

['Both Vertebral', ' Basilar', 'R ICA']

In [64]:
# labels[452]

['Both Vertebral', ' Basilar', 'R ICA']

In [65]:
# predicted_occlusions

['L vertebral']

In [66]:
# predicted_occlusions == labels[129]

False

In [67]:
import numpy as np
class test_occlusions:
    
    def __init__(self,df):
        self.df = df
        self.df_report_column = self.df["CTA CTP Report Text"]
        
        #For output excel file
        self.output_dir = ""
        
        #Class to extract desired portions of reports
        self.report_extractor = report_text_extractor(self.df_report_column)
        #Cerebral artery templates
        #NOT USED
        self.report_ca_templates = self.report_extractor.get_report_templates()
        #End 'Impression:' section
        self.impressions = self.report_extractor.get_impressions()
        #CTP Perfusion section
        self.ctp_sections = self.report_extractor.get_ctps()
        
        self.ctpve = ctp_volumes_extractor(self.ctp_sections)
        self.ctpve.extract_volumes()
        ##List of tuples of format (ischemic core volume,hypoperfusion volume)
        self.ctp_volumes = self.ctpve.get_volumes()
        
        #Goes reads through all templates and populates a dictionary
        self.ca_templates_reader = ca_templates_reader(self.df_report_column)
        self.ca_templates_reader.compile_regex()
        self.ca_templates_dicts = self.ca_templates_reader.read_templates()
        
        #Setting up pyConText
        self.mod_path = "/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/modifiers.yml"
        self.targ_path = "/mnt/c/Users/zohai/Documents/Research/Neuro_ML/Sample_Data/targets.yml"
        self.itemData_init = pyConText_itemData_initializer(self.mod_path,self.targ_path)
        self.modifiers = self.itemData_init.get_itemData()[0]
        self.targets = self.itemData_init.get_itemData()[1]
        
        #Finding possible occlusions based on cerebral arteries templates
        self.ca_to_investigate = []
        self.pogs = []
        for template in self.ca_templates_dicts:
            pog = possible_occlusions_generator(template)
            self.pogs.append(pog)
            self.ca_to_investigate.append(pog.get_possibilities())
        
        #Investigating the possible occlusions of the impressions of each report
        #Using pyConText (used by occlusions_investigator)
        
        
        #self.predicted_occlusions -> Raw occlusions found, used to populate self.occlusion_labels,
        # self.predicted_vessels, and self.predicted_segments
        self.predicted_occlusions = []
        #For debugging, -1 represents flag of uncertainty
        self.possibility_ratings = []
        self.markups = []
        self.unmatched_occlusion_sents = []
        self.uncertain_occlusions = []
        
        for possibilities,impression in zip(self.ca_to_investigate,self.impressions):
            
            
            oi = occlusions_investigator(possibilities,impression,self.modifiers,self.targets)
            self.predicted_occlusions.append(oi.get_occlusions())
            self.possibility_ratings.append(oi.get_possibility_ratings())
            self.markups.append(oi.get_markups())
            self.unmatched_occlusion_sents.append(oi.get_unmatched_occlusion_sents())
            self.uncertain_occlusions.append(oi.get_uncertain_occlusions())
            
            
        self.pred_occl_statuses = [0 if not occl else 1 for occl in self.predicted_occlusions]
        self.occl_status_labels = [1 if val > 0 else val for val in self.df['LVO']]
        
        self.pred_classifier = vessel_site_classifier(self.predicted_occlusions)
        self.predicted_vessels, self.predicted_segments = self.pred_classifier.classify()
        
        #Extracting labels to verify the predicted occlusions
        self.labels_extractor = labels_extractor(self.df['Side'],self.df['site occlusion'])
        self.labels = self.labels_extractor.return_labels()
        
        self.labels_classifier = vessel_site_classifier(self.labels)
        self.labeled_vessels, self.labeled_segments = self.labels_classifier.classify()        
                
        #self.differences = [(prediction,label) if list(set(map(self.lower,prediction))^set(map(self.lower,label))) 
                       #else () for prediction,label in zip(self.predicted_occlusions,self.labels) ]
        self.diffs = self.differences(self.predicted_occlusions,self.labels)
        #Indices of differences of occlusion status
        self.occl_status_diffs = np.where((abs(np.subtract(self.pred_occl_statuses,self.occl_status_labels)).astype(bool)))
        self.vessels_diffs = self.differences(self.predicted_vessels,self.labeled_vessels)
        self.segments_diffs = self.differences(self.predicted_segments,self.labeled_segments)
    

    
    def differences(self,preds,labels):
        #Compare lower case labels to lower case predictions
        #Set ^ operation returns list with elements unique to either prediction or label but not both
        lower = lambda x:x.lower()
        differences = []
        for prediction,label in zip(preds,labels):
            if list(set(map(lower,prediction))^set(map(lower,label))):
                differences.append((prediction,label))
            else:
                differences.append(())
        return differences
    
     
    #An uncertainty flag for user review
    #may show a template error
    #returns the sentences and report indices where occlusions are mentioned in the findings 
    #but the algo did not register any at those same cerebral arteries in template
    def get_unmatched_occlusions(self):
        return [(sent,i) for sent,i in zip(self.unmatched_occlusion_sents,range(len(self.unmatched_occlusion_sents))) if sent]
    
    #For user review of instances where occlusion is possible because of similar terms used, but occlusion not used
    def get_uncertain_occlusions(self):
        return [(uo,i) for uo,i in zip(self.uncertain_occlusions,range(len(self.uncertain_occlusions))) if uo] 
        #return self.uncertain_occlusions
    
    def get_occlusion_metrics(self):
            #Precision/PPV = TP/TP+FP i.e. out of true calls, how many actually true
            #Recall = TP/TP+FN i.e. out of all trues, how many algo called true
            #F1-score = Accuracy taking into account precision and recall
            print(classification_report(to.occl_status_labels,to.pred_occl_statuses))
            print(multilabel_confusion_matrix(to.occl_status_labels,to.pred_occl_statuses))
    
    def get_vessel_metrics(self):
        vessel_sg = stats_generator(self.predicted_vessels,self.labeled_vessels)
        vessel_sg.getStats()
        
    def get_segment_metrics(self):
        segment_sg = stats_generator(self.predicted_segments,self.labeled_segments)
        segment_sg.getStats()
        
    def get_side_metrics(self):
        side_sg = stats_generator(self.predicted_segments,self.labeled_segments,"sides")
        side_sg.getStats()
    
    def get_occlusion_accuracy(self):
        #Subtracts the 1's and 0's of the predicted and labeled occl statuses and turns them positive, sums, divides
        #by the total to get the error rate, then yields accuracy by 1-error_rate
        return(1-(sum(abs(np.subtract(self.pred_occl_statuses,self.occl_status_labels)))/len(self.occl_status_labels)))
    
    def get_vessel_accuracy(self):
        return self.get_accuracy(self.vessels_diffs)
    
    def get_segments_accuracy(self):
        return self.get_accuracy(self.segments_diffs)
    
    def get_raw_accuracy(self):
        return self.get_accuracy(self.diffs)
        
        
    def get_accuracy(self,diffs_list):
        score = 0
        for tup in diffs_list:
            if not tup:
                score += 1
        return(score/len(diffs_list))
    
    def get_volumes(self):
        return self.ctp_volumes
      
    #Writes to an excel file
    #(Takes input excel file, adds columns, and outputs it)
    #Input: Input excel file dataframe, input excel file path
    def write_to_excel(self,raw_df, raw_dir):
        output_df = raw_df
        self.output_dir = raw_dir.split(".")[0] + "_AUTOMATED_OCCLUSION_PREDICTIONS.xlsx"
        outputs = {"pred_occlusion": self.pred_occl_statuses,
                   "pred_vessels": self.predicted_vessels,
                   "pred_segments": self.predicted_segments,
                   "true_vessels": self.labeled_vessels,
                   "true_segments": self.labeled_segments,
                   "volumes": self.get_volumes(),
                   "unmatched_occlusions": self.unmatched_occlusion_sents,
                   "uncertain_occlusions": self.uncertain_occlusions
                  }
        for col_name, col_data in outputs.items():
            output_df[col_name] = col_data
        output_df.to_excel(self.output_dir,index=False)
    
    def get_output_excel_path(self):
        return self.output_dir
            
        
        
            
            
        
        
        
        
        

In [70]:
to = test_occlusions(filtered_df)
#print(to.report_ca_templates[90])


/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/pyConTextNLP/itemData.py:40: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  context_items =  [contextItem((d["Lex"],


In [71]:
# to.pred_occl_statuses

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,


In [72]:
# to.occl_status_labels

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,


In [73]:
to.get_occlusion_metrics()

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       422
           1       0.89      0.94      0.91       155

    accuracy                           0.95       577
   macro avg       0.93      0.95      0.94       577
weighted avg       0.95      0.95      0.95       577

[[[145  10]
  [ 18 404]]

 [[404  18]
  [ 10 145]]]


In [74]:
to.get_vessel_metrics()

              precision    recall  f1-score   support

         ACA       0.83      1.00      0.91         5
         CCA       0.33      0.25      0.29         4
         ICA       0.78      0.78      0.78        32
         MCA       0.94      0.96      0.95       112
         PCA       0.86      0.92      0.89        13
     basilar       0.33      1.00      0.50         3
   vertebral       0.60      0.92      0.73        13

   micro avg       0.83      0.91      0.87       182
   macro avg       0.67      0.83      0.72       182
weighted avg       0.85      0.91      0.88       182
 samples avg       0.24      0.25      0.24       182

[[[571   1]
  [  0   5]]

 [[571   2]
  [  3   1]]

 [[538   7]
  [  7  25]]

 [[458   7]
  [  5 107]]

 [[562   2]
  [  1  12]]

 [[568   6]
  [  0   3]]

 [[556   8]
  [  1  12]]]
0.925476603119584


/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/mnt/c/Users/zohai/Documents/Research/Neuro_ML/miniconda3/envs/neuroml/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [75]:
to.get_segment_metrics()

              precision    recall  f1-score   support

          A1       1.00      1.00      1.00         1
          A2       1.00      1.00      1.00         2
          A3       1.00      1.00      1.00         1
          M1       0.88      0.91      0.89        64
          M2       0.94      0.97      0.95        61
          M3       0.60      1.00      0.75         3
          P1       0.75      1.00      0.86         3
          P2       1.00      1.00      1.00         7
          V2       0.50      1.00      0.67         1
          V3       0.50      1.00      0.67         2
          V4       0.38      0.75      0.50         4

   micro avg       0.86      0.94      0.90       149
   macro avg       0.78      0.97      0.84       149
weighted avg       0.88      0.94      0.91       149
 samples avg       0.20      0.21      0.20       149

[[[576   0]
  [  0   1]]

 [[575   0]
  [  0   2]]

 [[576   0]
  [  0   1]]

 [[505   8]
  [  6  58]]

 [[512   4]
  [  2  59]]

 [[

In [76]:
to.get_side_metrics()

              precision    recall  f1-score   support

           L       0.89      0.99      0.94        69
           R       0.90      0.93      0.92        58

   micro avg       0.90      0.96      0.93       127
   macro avg       0.90      0.96      0.93       127
weighted avg       0.90      0.96      0.93       127
 samples avg       0.21      0.21      0.21       127

[[[500   8]
  [  1  68]]

 [[513   6]
  [  4  54]]]
0.9688041594454073


In [77]:
# from sklearn.metrics import confusion_matrix
# tn, fp, fn, tp = confusion_matrix(to.occl_status_labels,to.pred_occl_statuses).ravel()
# (tn, fp, fn, tp)

(404, 18, 10, 145)

In [78]:
# segs = list(zip(to.predicted_segments, to.labeled_segments))
# segs

[([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 (['L M2'], ['L M2']),
 (['R M1', 'R M2'], ['R M1', 'R M2']),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 (['L M1'], ['L M1']),
 (['R M2'], ['R M2']),
 ([], []),
 ([], []),
 (['L M2'], ['L M2']),
 ([], []),
 ([], []),
 ([], []),
 (['L M2'], ['L M2']),
 (['L M2'], ['L M2']),
 ([], []),
 ([], []),
 (['L M2'], ['L M2']),
 ([], []),
 (['L V3', 'L V4'], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 (['L M2'], ['L M2']),
 ([], []),
 ([], []),
 ([], []),
 (['R P2'], ['R P2']),
 ([], []),
 (['L M2'], ['L M2']),
 ([], []),
 ([], []),
 ([], []),
 (['R M1'], ['R M1']),
 ([], []),
 ([], []),
 (['L M1'], ['L M1']),
 ([], []),
 ([], []),
 ([], []),
 (['L M1'], ['L M1']),
 ([], []),
 ([], []),
 (['R M1'], ['R M1']),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 ([], []),
 (['L V3', 'L V4'], ['L V3', 'L V4']),
 (['R M1'], ['R M1']),
 (['R V4'], ['R V4']),
 (['R M2'], ['R M2']),


In [79]:
# o = ['L M1', ' basilar', 'M']
# seg_m1 = lambda x: int(not not sum(["M1" in l for l in x]))
# seg_m2 = lambda x: int(not not sum(["M2" in l for l in x]))
# seg_m2(o)

0

In [80]:
# #Only M1 or M2s in segs
# segs = [(segs[i][0],segs[i][1]) for i in range(len(segs)) if (seg_m1(segs[i][1]) or seg_m2(segs[i][1]))]
# segs

[(['L M2'], ['L M2']),
 (['R M1', 'R M2'], ['R M1', 'R M2']),
 (['L M1'], ['L M1']),
 (['R M2'], ['R M2']),
 (['L M2'], ['L M2']),
 (['L M2'], ['L M2']),
 (['L M2'], ['L M2']),
 (['L M2'], ['L M2']),
 (['L M2'], ['L M2']),
 (['L M2'], ['L M2']),
 (['R M1'], ['R M1']),
 (['L M1'], ['L M1']),
 (['L M1'], ['L M1']),
 (['R M1'], ['R M1']),
 (['R M1'], ['R M1']),
 (['R M2'], ['R M2']),
 (['L M1', 'L M2'], ['L M1', 'L M2']),
 (['L M2'], ['L M2']),
 (['L M1', 'L M2'], ['L M1', 'L M2']),
 (['R M1'], ['R M1']),
 (['L M1'], ['L M1']),
 (['L M1'], ['L M1']),
 ([], ['R M1', 'R M2']),
 (['L M2'], ['L M2']),
 (['L M1'], ['L M1']),
 (['R M1', 'R M2'], ['R M1', 'R M2']),
 (['L M1'], ['L M1']),
 (['L M1'], ['L M1']),
 (['R M2', 'R M3'], ['R M2', 'R M3']),
 (['L M2'], ['L M2']),
 (['R M1'], ['R M1']),
 (['L M2'], ['L M2']),
 (['R M2'], ['R M1', 'R M2']),
 (['R M1', 'R M2', 'R M3'], ['R M1']),
 (['R M2'], ['R M2']),
 (['L M1'], ['L M1']),
 (['R M1'], ['R M1']),
 (['R M2'], ['R M2']),
 (['R M1'], ['R M1']

In [81]:
# len(segs)

108

In [82]:
# seg_m1_status_df = pd.DataFrame([(seg_m1(p),seg_m1(l)) for (p,l) in segs])
# seg_m1_status_df.columns = ["predicted","labels"]
# seg_m1_status_df

predicted  labels
0            0       0
1            1       1
2            1       1
3            0       0
4            0       0
..         ...     ...
103          0       0
104          1       1
105          1       1
106          0       0
107          0       0

[108 rows x 2 columns]

In [83]:
# seg_m1_df = pd.DataFrame([(seg_m1(p),seg_m1(l)) for (p,l) in segs])
# seg_m1_df.columns = ["predicted","labels"]
# seg_m2_df = pd.DataFrame([(seg_m2(p),seg_m2(l)) for (p,l) in segs])
# seg_m2_df.columns = ["predicted","labels"]
# seg_m1_df

In [84]:
# seg_m2_df

In [85]:
# seg_m1_df.labels.sum()

In [86]:
# seg_m1_df.predicted.sum()

In [87]:
# seg_m2_df.labels.sum()

In [88]:
# seg_m2_df.predicted.sum()

In [89]:
# print(classification_report(seg_m1_status_df.labels, seg_m1_status_df.predicted))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90        44
           1       0.95      0.91      0.93        64

    accuracy                           0.92       108
   macro avg       0.91      0.92      0.91       108
weighted avg       0.92      0.92      0.92       108



In [90]:
# from sklearn.metrics import confusion_matrix
# tn, fp, fn, tp = confusion_matrix(seg_m1_status_df.labels, seg_m1_status_df.predicted).ravel()
# (tn, fp, fn, tp)

(41, 3, 6, 58)

In [91]:
# seg_m2_df = pd.DataFrame([(seg_m2(p),seg_m2(l)) for (p,l) in segs])
# seg_m2_df.columns = ["predicted","labels"]
# seg_m2_df[seg_m2_df["labels"]>0]


predicted  labels
0            1       1
1            1       1
3            1       1
4            1       1
5            1       1
..         ...     ...
102          1       1
103          0       1
105          1       1
106          1       1
107          1       1

[61 rows x 2 columns]

In [92]:
# print(classification_report(seg_m2_df.labels, seg_m2_df.predicted))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96        47
           1       0.97      0.97      0.97        61

    accuracy                           0.96       108
   macro avg       0.96      0.96      0.96       108
weighted avg       0.96      0.96      0.96       108



In [93]:
# from sklearn.metrics import confusion_matrix
# tn, fp, fn, tp = confusion_matrix(seg_m2_df.labels,seg_m2_df.predicted).ravel()
# (tn, fp, fn, tp)

(45, 2, 2, 59)

In [94]:
# to.predicted_vessels[163]

['L ICA']

In [95]:
# to.labeled_vessels[163]

['L ICA']

In [96]:
# output_df = raw_df
# output_dir = raw_dir.split(".")[0] + "_AUTOMATED_OCCLUSION_PREDICTIONS.xlsx"
# outputs = {"pred_occlusion":to.pred_occl_statuses,
#            "pred_vessels":to.predicted_vessels,
#            "pred_segments":to.predicted_segments,
#            "volumes":to.get_volumes()
#           }
# for col_name, col_data in outputs.items():
#     output_df[col_name] = col_data

# output_df.to_excel(output_dir,index=False)

In [97]:
to.write_to_excel(raw_df,raw_dir)
print("save complete")

In [98]:
# pd.read_excel(to.get_output_excel_path()).head()

Organization Point of Care  Accession Number Exam Code  \
0          BJH      BJH 0092          53737770    IMG575   
1          BJH        BJH ED          53736230    IMG575   
2          BJH        BJH ED          53728765    IMG575   
3          BJH        BJH ED          53728726    IMG575   
4          BJH      BJH 0105          53718900    IMG575   

           Exam Description  LVO Comments Side Site Carotid stenosis  ...  \
0  CTA/CTP RAPID STROKE (C)    0      NaN  NaN  NaN              NaN  ...   
1  CTA/CTP RAPID STROKE (C)    0      NaN  NaN  NaN              NaN  ...   
2  CTA/CTP RAPID STROKE (C)    0      NaN  NaN  NaN              NaN  ...   
3  CTA/CTP RAPID STROKE (C)    0      NaN  NaN  NaN              NaN  ...   
4  CTA/CTP RAPID STROKE (C)    0      NaN  NaN  NaN              NaN  ...   

   Report Created to Report Finalized (minutes)  \
0                                          12.0   
1                                          70.0   
2                                         164.0   
3                                         407.0   
4                                        1731.0   

   Preliminary Report to Report Finalized (minutes)  pred_occlusion  \
0                                               3.0               0   
1                                              10.0               0   
2                                             126.0               0   
3                                             370.0               0   
4                                            1724.0               0   

  pred_vessels pred_segments true_vessels  true_segments  volumes  \
0           []            []           []             []   (0, 0)   
1           []            []           []             []  (13, 5)   
2           []            []           []             []   (0, 8)   
3           []            []           []             []   (0, 0)   
4           []            []           []             []   (0, 5)   

  unmatched_occlusions                               uncertain_occlusions  
0                   []                                                 []  
1                   []  [('uncertain occlusion', 'vertebral', '  _x000...  
2                   []                                                 []  
3                   []                                                 []  
4                   []                                                 []  

[5 rows x 48 columns]

In [99]:
# bin_pred_vessels = mlb_fit.transform(to.predicted_vessels)
# bin_labeled_vessels = mlb_fit.transform(to.labeled_vessels)
# metrics.confusion_matrix(bin_labeled_vessels.argmax(axis=1), bin_pred_vessels.argmax(axis=1), labels=mlb_fit.classes_)

In [100]:
to.occl_status_diffs

(array([ 71,  72,  73,  87, 109, 114, 125, 137, 203, 210, 235, 241, 283,
        301, 306, 334, 345, 359, 387, 403, 404, 418, 419, 452, 516, 528,
        537, 568]),)

In [101]:
# to.vessels_diffs

[(),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([], ['L MCA', 'L ICA']),
 (['L MCA', 'L ICA'], ['L ICA']),
 ([], ['L vertebral', 'R vertebral']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['R ICA', 'L ICA'], []),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([], ['R MCA']),
 (),
 (),
 (),
 (),
 (['L vertebral'], []),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([], ['R ICA']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([' basilar'], []),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([' basilar', 'L vertebral', 'R vertebral'], [' vertebral', '

In [102]:
# to.labeled_vessels

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 ['L MCA'],
 ['R ICA', 'R MCA'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['L MCA', 'L ICA', 'L ACA'],
 ['R MCA'],
 [],
 [],
 ['L MCA'],
 [],
 [],
 [],
 ['L MCA'],
 ['L MCA'],
 [],
 [],
 ['L MCA'],
 [],
 ['L vertebral'],
 [],
 [],
 [],
 [],
 [],
 ['L MCA'],
 [],
 [],
 [],
 ['R PCA'],
 [],
 ['L MCA'],
 [],
 [],
 [],
 ['R MCA'],
 [],
 [],
 ['L MCA'],
 ['L ICA'],
 [],
 [],
 ['L MCA'],
 [],
 [],
 ['R MCA'],
 [],
 [],
 [],
 [],
 [],
 ['L vertebral'],
 ['R MCA'],
 ['R vertebral'],
 ['R MCA'],
 [],
 [],
 [],
 [],
 [],
 ['L MCA', 'L ICA'],
 ['L ICA'],
 ['L vertebral', 'R vertebral'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['L MCA'],
 ['L MCA'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['L MCA'],
 [],
 ['R MCA'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['L MCA'],
 [],
 [],
 [],
 ['L MCA', 'L ICA'],
 [],
 [],
 [],
 [],
 ['R MCA'],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ['R ICA'],
 [],
 [],
 [],
 ['R vertebral'],
 [],
 [],
 [],
 [],
 [],
 ['L

In [103]:
to.get_raw_accuracy()

0.8492201039861352

In [104]:
to.get_occlusion_accuracy()

0.951473136915078

In [105]:
to.get_vessel_accuracy()

0.9133448873483535

In [106]:
to.get_segments_accuracy()

0.951473136915078

In [107]:
diffs = to.diffs
# diffs

[(),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['R ICA', 'R MCA', 'R M1', 'R M2'], ['R ICA', 'R M1', 'R M2']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['L MCA', 'L M2'], ['L M2']),
 (),
 (),
 (),
 (['L MCA', 'L M2'], ['L M2']),
 (),
 (['L vertebral', 'L V3', 'L V4'], ['L vertebral']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['R PCA', 'R P2'], ['R P2']),
 (),
 (),
 (),
 (),
 (),
 (['R M1'], ['R M1', 'R Vetebral']),
 (),
 (),
 (),
 (),
 (),
 (),
 (['L MCA', 'L M1'], ['L M1']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['L vertebral', 'L V3', 'L V4'], ['L V3', 'L V4']),
 (['R MCA', 'R M1'], ['R M1']),
 (['R vertebral', 'R V4'], ['R V4']),
 (),
 (),
 (),
 (),
 (),
 (),
 ([], ['L ICA', 'L MCA']),
 (['L ICA', 'L M1'], ['L ICA']),
 ([], ['R V4', 'L V4']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['L ICA', 'R ICA'], []),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([],

In [108]:
# to.segments_diffs

[(),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['L V3', 'L V4'], []),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (['L M1'], []),
 ([], ['R V4', 'L V4']),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 ([], ['R M1', 'R M2']),
 (),
 (),
 (),
 (),
 (['L V4'], []),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 (),
 

In [109]:
ind_vessels_diffs = list(filter(lambda xy:True if xy[0] else False,(zip(to.vessels_diffs,range(len(to.vessels_diffs))))))
ind_vessels_diffs

[(([], ['L MCA', 'L ICA']), 71),
 ((['L MCA', 'L ICA'], ['L ICA']), 72),
 (([], ['L vertebral', 'R vertebral']), 73),
 ((['R ICA', 'L ICA'], []), 87),
 (([], ['R MCA']), 109),
 ((['L vertebral'], []), 114),
 (([], ['R ICA']), 125),
 (([' basilar'], []), 137),
 (([' basilar', 'L vertebral', 'R vertebral'], [' vertebral', ' basilar']),
  154),
 ((['R ICA', 'R MCA'], ['R MCA']), 155),
 ((['L vertebral', ' basilar', 'R vertebral'], ['L vertebral', 'R vertebral']),
  183),
 ((['L MCA', 'L ICA'], ['L CCA']), 203),
 ((['R ICA'], []), 210),
 ((['L MCA', 'R vertebral'], ['L MCA']), 218),
 ((['R ICA', 'R MCA'], ['R ICA']), 231),
 ((['L MCA'], []), 241),
 ((['L PCA', ' basilar', 'L vertebral'], ['L vertebral']), 242),
 (([], ['R ICA']), 273),
 ((['R ICA', 'R MCA', 'R ACA'], ['R ICA']), 280),
 (([' basilar'], []), 301),
 (([], ['R ICA']), 306),
 (([], ['R ICA']), 315),
 ((['R PCA', 'R vertebral'], ['R vertebral']), 325),
 (([], ['L CCA']), 330),
 ((['L MCA', 'R MCA'], ['L MCA']), 331),
 ((['L vert

In [110]:
unmatched_occlusion_sents = to.get_unmatched_occlusions()
unmatched_occlusion_sents

[(["_x000D__x000D_Of note, the perfusion data is likely inaccurate due to patient's poor cardiac output, however, the decreased perfusion within the right anterior watershed zone between the ACA and MCA is likely secondary to decreased systemic perfusion rather than a focal occlusion"],
  31),
 (['_x000D_No intracranial large vessel occlusion nor ischemic core on CT perfusion'],
  58),
 (['_x000D__x000D_No intracranial large vessel occlusion or stenosis'], 79),
 (['  Occlusion of a left superior division M3 on CTA with associated 11 mm brain at risk, but no infarct core'],
  97),
 ([' The left posterior inferior cerebellar artery takes off just distal to this occlusion and appears patent'],
  114),
 (['  This is likely the site of occlusion'], 125),
 (['  There is also 90% occlusion of the left subclavian artery origin which reconstitutes distally'],
  137),
 ([' Distal left MCA branches paucity/occlusion with reconstitution distally (axial series 10 image 180-194 and 145-165)'],
  168

In [111]:
uncertain_occlusions = to.get_uncertain_occlusions()
#uncertain_occlusions= [x for x in uncertain_occlusions if x]
uncertain_occlusions

[([('uncertain occlusion',
    'vertebral',
    '  _x000D_Non-opacification of the right vertebral artery at its origin with reconstitution distally')],
  1),
 ([('uncertain occlusion',
    'vertebral',
    '  _x000D__x000D_Abrupt cut off of the left vertebral artery slightly before junction with the right at the level of V3-V4 consistent with post surgical ligation or dissection with backfilling and retrograde filling of left PICA from the basilar confluence'),
   ('uncertain occlusion',
    'V3',
    '  _x000D__x000D_Abrupt cut off of the left vertebral artery slightly before junction with the right at the level of V3-V4 consistent with post surgical ligation or dissection with backfilling and retrograde filling of left PICA from the basilar confluence'),
   ('uncertain occlusion',
    'V4',
    '  _x000D__x000D_Abrupt cut off of the left vertebral artery slightly before junction with the right at the level of V3-V4 consistent with post surgical ligation or dissection with backfillin

In [112]:
ind_diffs = [ind for sent,ind in ind_vessels_diffs]
ind_unmatched = [ind for sent,ind in unmatched_occlusion_sents]
list(set(np.ndarray.tolist(to.occl_status_diffs[0]))&set(ind_unmatched))

[419, 452, 137, 334, 114, 125]

In [113]:
ind_vessels_diffs
#5 missed occls 419,452, 125, 516, 109
#4 falsely called occl 137, 334, 114, 528

[(([], ['L MCA', 'L ICA']), 71),
 ((['L MCA', 'L ICA'], ['L ICA']), 72),
 (([], ['L vertebral', 'R vertebral']), 73),
 ((['R ICA', 'L ICA'], []), 87),
 (([], ['R MCA']), 109),
 ((['L vertebral'], []), 114),
 (([], ['R ICA']), 125),
 (([' basilar'], []), 137),
 (([' basilar', 'L vertebral', 'R vertebral'], [' vertebral', ' basilar']),
  154),
 ((['R ICA', 'R MCA'], ['R MCA']), 155),
 ((['L vertebral', ' basilar', 'R vertebral'], ['L vertebral', 'R vertebral']),
  183),
 ((['L MCA', 'L ICA'], ['L CCA']), 203),
 ((['R ICA'], []), 210),
 ((['L MCA', 'R vertebral'], ['L MCA']), 218),
 ((['R ICA', 'R MCA'], ['R ICA']), 231),
 ((['L MCA'], []), 241),
 ((['L PCA', ' basilar', 'L vertebral'], ['L vertebral']), 242),
 (([], ['R ICA']), 273),
 ((['R ICA', 'R MCA', 'R ACA'], ['R ICA']), 280),
 (([' basilar'], []), 301),
 (([], ['R ICA']), 306),
 (([], ['R ICA']), 315),
 ((['R PCA', 'R vertebral'], ['R vertebral']), 325),
 (([], ['L CCA']), 330),
 ((['L MCA', 'R MCA'], ['L MCA']), 331),
 ((['L vert

In [114]:
len(unmatched_occlusion_sents)

20

In [115]:
len(ind_vessels_diffs)

50

In [116]:
ind_diffs = [ind for sent,ind in ind_vessels_diffs]
ind_uncertain = [ind for sent,ind in uncertain_occlusions]
list(set(np.ndarray.tolist(to.occl_status_diffs[0]))&set(ind_uncertain))

[419, 516, 137, 109, 528]

In [117]:
len(uncertain_occlusions)

29